baseURL = 'https://asdrome.com/'
defaultContentLanguage = 'en'
title = 'Material Hugo'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.122.0"

[languages]
  [languages.en]
    languageName= 'English'
    contentDir= 'content/en'
    weight= 1
    disabled= false

  [languages.es]
    languageName= 'Español'
    contentDir= 'content/es'
    weight= 2
    disabled= false